name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with: { fetch-depth: 0, fetch-tags: true }

      - uses: mlugg/setup-zig@v2
        id: setup-zig
        with: { version: 0.15.2 }

      - uses: denoland/setup-deno@v2
        id: setup-deno
        with: { deno-version: v2.x }

      - name: Run tests
        run: zig build test

      - name: Build plugin (ReleaseSmall)
        run: zig build -Doptimize=ReleaseSmall

      - name: Generate release notes
        run: |
          git fetch origin --tags --force
          deno run -A scripts/generate_release_notes.ts "$GITHUB_REF_NAME" > release_notes.md

      - name: Upload plugin artifact
        uses: actions/upload-artifact@v6
        with:
          name: plugin
          path: zig-out/bin/plugin.wasm

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            zig-out/bin/plugin.wasm
            schema.json
          body_path: release_notes.md

  publish-jsr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - uses: denoland/setup-deno@v2
        id: setup-deno
        with: { deno-version: v2.x }

      - name: Publish to JSR
        run: deno run -A scripts/publish_jsr.ts

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v6

      - uses: denoland/setup-deno@v2
        id: setup-deno
        with: { deno-version: v2.x }

      - uses: actions/setup-node@v6
        id: setup-node
        with: { node-version: 22, registry-url: https://registry.npmjs.org }

      - name: Update npm # OIDC provenance requires npm 11.5.1+
        run: npm i -g npm@latest

      - name: Publish to NPM
        run: deno run -A scripts/publish_npm.ts
        # env: # Turned off as we are using OIDC for authentication
        #   NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
